# -*- coding: utf-8 -*-
"""GeoSpatial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-KIBOcnM-41iWEt0ymAXnE7macPoIgK
"""

import geopandas as gpd

url = "https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip"

world = gpd.read_file(url)

world.plot()

pip install osmnx

import osmnx as ox

gdf = ox.geocode_to_gdf("Delhi, India")

gdf.plot()

# View first rows
print(gdf.head())

# CRS (coordinate system)
print(gdf.crs)

# Geometry type
print(gdf.geometry.type)

# Columns
print(gdf.columns)

# Project to UTM (meters)
gdf_proj = gdf.to_crs(epsg=32643)   # UTM zone for Delhi

# Area (in sq km)
gdf_proj["area_sqkm"] = gdf_proj.area / 1e6

# Perimeter (in km)
gdf_proj["perimeter_km"] = gdf_proj.length / 1000

print(gdf_proj[["area_sqkm", "perimeter_km"]])

# Download road network
G = ox.graph_from_place("Kochi, India", network_type="drive")

# Plot roads
ox.plot_graph(G)

stats = ox.basic_stats(G)

for k, v in stats.items():
    print(k, ":", v)

from shapely.geometry import Polygon

# Get polygon
polygon = gdf.geometry.iloc[0]

# Download buildings
buildings = ox.features_from_polygon(
    polygon,
    tags={"building": True}
)

print("Number of buildings:", len(buildings))

buildings.plot()

area = gdf_proj["area_sqkm"].iloc[0]

density = len(buildings) / area

print("Building Density per sq km:", density)

# Count buildings per ward (if available)
buildings["centroid"] = buildings.centroid

buildings.plot(markersize=1)

green = ox.features_from_polygon(
    polygon,
    tags={"leisure": "park"}
)

green.plot(color="green")

print("Number of parks:", len(green))

# Save buildings
buildings_to_save = buildings.drop(columns=['centroid'])
buildings_to_save.to_file("delhi_buildings.geojson", driver="GeoJSON")

# Save roads
ox.save_graphml(G, "delhi_roads.graphml")

# Convert geometry to centroids
buildings["centroid"] = buildings.geometry.centroid

# Extract lat/lon
buildings["lat"] = buildings.centroid.y
buildings["lon"] = buildings.centroid.x

buildings_tabular = buildings.drop(columns=["geometry", "centroid"])
buildings_tabular.to_excel("delhi_buildings.xlsx", index=False)
files.download("delhi_buildings.xlsx")