# -*- coding: utf-8 -*-
"""Web Scrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxjiYOTWwmeuBA57bNLdZnC4_8Xutlts
"""

import pandas as pd
df = pd.read_html("https://fbref.com/en/comps/Big5/2024-2025/wages/2024-2025-Big-5-European-Leagues-Wages", attrs={"id":"squad_wages"})